### ISSUE TITLE
InfiniteEmotes

### ISSUE THREAD

**Issue by Bunxxx** [KlutzyBubbles/lc-infinite-emote#1]
currently having an issue where infiniteemote mod is making it so i cannot move. im able to turn and jump but its almost as if movement speed is decreased to the point u are basically just moonwalking. looking forward to using this mod again in the future once the issues been resolved though!

**Comment by KlutzyBubbles** [comment]
> currently having an issue where infiniteemote mod is making it so i cannot move. im able to turn and jump but its almost as if movement speed is decreased to the point u are basically just moonwalking. looking forward to using this mod again in the future once the issues been resolved though!

This mod does nothing to movement speed however it does change the return value of 'CheckConditionsForEmote' which some other mods use to check whether an emote can be performed.

What i think is happening here is you have another emote mod that is expecting the player to stand still while emoting and is just setting the speed to 0 whenever CheckConditionsForEmote is true, instead of just disabling player input. But i can only be sure if i get the mod list from you.

**Comment by FirewallDaProtogen** [comment]
> > currently having an issue where infiniteemote mod is making it so i cannot move. im able to turn and jump but its almost as if movement speed is decreased to the point u are basically just moonwalking. looking forward to using this mod again in the future once the issues been resolved though!
> 
> This mod does nothing to movement speed however it does change the return value of 'CheckConditionsForEmote' which some other mods use to check whether an emote can be performed.
> 
> What i think is happening here is you have another emote mod that is expecting the player to stand still while emoting and is just setting the speed to 0 whenever CheckConditionsForEmote is true, instead of just disabling player input. But i can only be sure if i get the mod list from you.

idk. i'm also having this issue.
for testing purposes i made a new r2modman profile with only the infiniteemotes installed (and its dependencies) and it doesnt work. However, upon adding More_Emotes by Sligili, it no longer works
i think this problem is on their end? idk

**Comment by KlutzyBubbles** [comment]
> > > currently having an issue where infiniteemote mod is making it so i cannot move. im able to turn and jump but its almost as if movement speed is decreased to the point u are basically just moonwalking. looking forward to using this mod again in the future once the issues been resolved though!
> > 
> > 
> > This mod does nothing to movement speed however it does change the return value of 'CheckConditionsForEmote' which some other mods use to check whether an emote can be performed.
> > What i think is happening here is you have another emote mod that is expecting the player to stand still while emoting and is just setting the speed to 0 whenever CheckConditionsForEmote is true, instead of just disabling player input. But i can only be sure if i get the mod list from you.
> 
> idk. i'm also having this issue. for testing purposes i made a new r2modman profile with only the infiniteemotes installed (and its dependencies) and it doesnt work. However, upon adding More_Emotes by Sligili, it no longer works i think this problem is on their end? idk

This might be an issue i saw when making this mod resurfacing. It was the whole reason i also made better emotes (because infinite emotes wasnt working with sligilis version).

But ufortunately like i have said to others in other issues, i dont have access to my computer for ~2 weeks over the christmas period so the best i can do is look at code an speculate to what the issue would be a fix it after.

Sorry i cannot fix it sooner :/

**Comment by codyalden** [comment]
For additional info, I have had this mod as in combination with MoreEmotes from sligili for the ~past 2 weeks without an issue. This problem of being stuck in place only started occurring for me at the same time of this issue posting. I don't know if there was some kind of hotfix to the game as the changelog doesn't have anything past the frosty update.

**Comment by KlutzyBubbles** [comment]
> For additional info, I have had this mod as in combination with MoreEmotes from sligili for the ~past 2 weeks without an issue. This problem of being stuck in place only started occurring for me at the same time of this issue posting. I don't know if there was some kind of hotfix to the game as the changelog doesn't have anything past the frosty update.

Just want to check it isnt the same issue as i was having on BetterEmotes https://github.com/KlutzyBubbles/lc-better-emotes/issues/10. 

Basically InputUtils (a library these mods depend on for keybindings) updated and would error when registering keybinds. Downgrading to InputUtils 0.4.2 removes the error.

Are you able to try with the InputUtils 0.4.2 to see if it makes any difference? i am unable to test as i am away and all i have access to is a macbook ;-;

**Comment by lemnrt** [comment]
Using InputUtils 0.4.2 works!

**Comment by KlutzyBubbles** [comment]
Closing as i believe the issue has been fixed since updating to InputUtils 0.4.4
