### ISSUE TITLE
Moving cancels emote

### ISSUE THREAD

**Issue by bubin7766** [KlutzyBubbles/lc-infinite-emote#2]
On the latest [More Emotes](https://thunderstore.io/c/lethal-company/p/Sligili/More_Emotes/) update, Moving while emoting with the new emotes on 9 and 0 just cancels the emote

**Comment by KlutzyBubbles** [comment]
I have fixed this in [v1.3.2](https://github.com/KlutzyBubbles/lc-infinite-emote/releases/tag/v1.3.2). Let me know if there are any other issues
